<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>SnowsCameraMod</AssemblyName>
    <RootNamespace>SnowsCameraMod</RootNamespace>
    <OutputPath>bin\\$(Configuration)\\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="BepInEx"><HintPath>libs\\BepInEx.dll</HintPath></Reference>
    <Reference Include="0Harmony"><HintPath>libs\\0Harmony.dll</HintPath></Reference>
    <Reference Include="Assembly-CSharp"><HintPath>libs\\Assembly-CSharp.dll</HintPath></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>libs\\UnityEngine.CoreModule.dll</HintPath></Reference>
    <Reference Include="UnityEngine.IMGUIModule"><HintPath>libs\\UnityEngine.IMGUIModule.dll</HintPath></Reference>
    <Reference Include="UnityEngine.InputLegacyModule"><HintPath>libs\\UnityEngine.InputLegacyModule.dll</HintPath></Reference>
    <Reference Include="UnityEngine.PhysicsModule"><HintPath>libs\\UnityEngine.PhysicsModule.dll</HintPath></Reference>
  </ItemGroup>
</Project>