<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>SnowsCameraPlus</AssemblyName>
    <RootNamespace>SnowsCameraPlus</RootNamespace>
    <OutputPath>bin\$(Configuration)\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="BepInEx"><HintPath>..\libs\BepInEx.dll</HintPath></Reference>
    <Reference Include="UnityEngine"><HintPath>..\libs\UnityEngine.dll</HintPath></Reference>
    <Reference Include="UnityEngine.CoreModule"><HintPath>..\libs\UnityEngine.CoreModule.dll</HintPath></Reference>
    <Reference Include="UnityEngine.TextRenderingModule"><HintPath>..\libs\UnityEngine.TextRenderingModule.dll</HintPath></Reference>
    <Reference Include="UnityEngine.IMGUIModule"><HintPath>..\libs\UnityEngine.IMGUIModule.dll</HintPath></Reference>
    <Reference Include="SnowsCameraFree"><HintPath>..\Free\bin\Release\SnowsCameraFree.dll</HintPath></Reference>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="All" />
  </ItemGroup>
</Project>